[2025-01-24T15:47:33.876+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T15:47:33.893+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-24T15:47:32.538589+00:00 [queued]>
[2025-01-24T15:47:33.905+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-24T15:47:32.538589+00:00 [queued]>
[2025-01-24T15:47:33.907+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T15:47:33.925+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt_model> on 2025-01-24 15:47:32.538589+00:00
[2025-01-24T15:47:33.937+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dbt_dag', 'run_dbt_model', 'manual__2025-01-24T15:47:32.538589+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dbt_dag.py', '--cfg-path', '/tmp/tmp5_irqvej']
[2025-01-24T15:47:33.940+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask run_dbt_model
[2025-01-24T15:47:33.942+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=845) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-24T15:47:33.944+0000] {standard_task_runner.py:72} INFO - Started process 846 to run task
[2025-01-24T15:47:33.995+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-24T15:47:32.538589+00:00 [running]> on host a9173c7a3aa2
[2025-01-24T15:47:34.087+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dbt_dag' AIRFLOW_CTX_TASK_ID='run_dbt_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T15:47:32.538589+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T15:47:32.538589+00:00'
[2025-01-24T15:47:34.088+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T15:47:41.601+0000] {logging_mixin.py:190} INFO - 15:47:38  Running with dbt=1.6.1
15:47:38  Registered adapter: postgres=1.6.1
15:47:38  Unable to do partial parsing because profile has changed
15:47:40  Found 4 models, 2 seeds, 2 sources, 0 exposures, 0 metrics, 464 macros, 0 groups, 0 semantic models
15:47:40  
15:47:40  Concurrency: 1 threads (target='dev')
15:47:40  
15:47:40  1 of 1 START sql table model jin_schema.my_first_dbt_model ..................... [RUN]
15:47:40  1 of 1 OK created sql table model jin_schema.my_first_dbt_model ................ [SELECT 2 in 0.13s]
15:47:40  
15:47:40  Finished running 1 table model in 0 hours 0 minutes and 0.21 seconds (0.21s).
15:47:40  
15:47:40  Completed successfully
15:47:40  
15:47:40  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-01-24T15:47:41.602+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T15:47:41.611+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T15:47:41.612+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dbt_dag, task_id=run_dbt_model, run_id=manual__2025-01-24T15:47:32.538589+00:00, execution_date=20250124T154732, start_date=20250124T154733, end_date=20250124T154741
[2025-01-24T15:47:41.613+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: slack_success_callback
[2025-01-24T15:47:41.613+0000] {taskinstance.py:1567} ERROR - Error in callback at index 0: slack_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1565, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/my_first_dbt_dag.py", line 35, in slack_success_callback
    success_task_alert = SlackWebhookOperator(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 489, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'slack_webhook_conn_id'
[2025-01-24T15:47:41.671+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T15:47:41.692+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T15:47:41.696+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
