[0m21:28:11.438053 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028AE99B4B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028AE99B6A80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028AE99B5A00>]}


============================== 21:28:11.444166 | 457d6450-36c1-4a2c-8e54-a3d377f21994 ==============================
[0m21:28:11.444166 [info ] [MainThread]: Running with dbt=1.9.1
[0m21:28:11.445087 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\jigna\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m21:28:11.446077 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jigna\dbt_airflow_jin\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:28:11.447058 [debug] [MainThread]: Command `dbt build` failed at 21:28:11.447058 after 0.20 seconds
[0m21:28:11.447058 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028AE9BB4200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028AE9E1EE70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028AE9A5F4A0>]}
[0m21:28:11.448066 [debug] [MainThread]: Flushing usage events
[0m21:28:11.968566 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m21:28:20.098584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A82F00BE30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A82F910470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A82FF699A0>]}


============================== 21:28:20.101592 | ddc58ee0-3359-4fdd-8e6c-a45e3e0e9b17 ==============================
[0m21:28:20.101592 [info ] [MainThread]: Running with dbt=1.9.1
[0m21:28:20.102671 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\jigna\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:28:20.103677 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jigna\dbt_airflow_jin\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:28:20.103677 [debug] [MainThread]: Command `dbt deps` failed at 21:28:20.103677 after 0.15 seconds
[0m21:28:20.104924 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A82F983350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A82F23FBC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A82F76ADE0>]}
[0m21:28:20.104924 [debug] [MainThread]: Flushing usage events
[0m21:28:20.579842 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:53:45.411998 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D7E831940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D7E640470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D7E114AA0>]}


============================== 18:53:45.418235 | a0c6f83e-9e18-4383-86c2-f7eb85bc7c7f ==============================
[0m18:53:45.418235 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:53:45.418766 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\jigna\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:53:45.445932 [info ] [MainThread]: dbt version: 1.9.1
[0m18:53:45.446906 [info ] [MainThread]: python version: 3.12.4
[0m18:53:45.447905 [info ] [MainThread]: python path: C:\Users\jigna\AppData\Local\Programs\Python\Python312\python.exe
[0m18:53:45.449903 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m18:53:45.523072 [info ] [MainThread]: Using profiles dir at C:\Users\jigna\.dbt
[0m18:53:45.524241 [info ] [MainThread]: Using profiles.yml file at C:\Users\jigna\.dbt\profiles.yml
[0m18:53:45.525249 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\jigna\dbt_airflow_jin\dbt_project.yml
[0m18:53:45.526426 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m18:53:45.527939 [debug] [MainThread]: Command `dbt debug` failed at 18:53:45.526933 after 0.32 seconds
[0m18:53:45.527939 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D7BC0A1E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D78835B80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022D7E93FEC0>]}
[0m18:53:45.527939 [debug] [MainThread]: Flushing usage events
[0m18:53:45.970348 [debug] [MainThread]: An error was encountered while trying to flush usage events
