[2025-01-12T13:51:55.528+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-12T13:51:55.543+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:51:54.671988+00:00 [queued]>
[2025-01-12T13:51:55.550+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:51:54.671988+00:00 [queued]>
[2025-01-12T13:51:55.551+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-12T13:51:55.565+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt_model> on 2025-01-12 13:51:54.671988+00:00
[2025-01-12T13:51:55.573+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dbt_dag', 'run_dbt_model', 'manual__2025-01-12T13:51:54.671988+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dbt_dag.py', '--cfg-path', '/tmp/tmpswaqdml7']
[2025-01-12T13:51:55.577+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask run_dbt_model
[2025-01-12T13:51:55.578+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=965) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-12T13:51:55.579+0000] {standard_task_runner.py:72} INFO - Started process 966 to run task
[2025-01-12T13:51:55.620+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:51:54.671988+00:00 [running]> on host 10a7333bcdf9
[2025-01-12T13:51:55.705+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dbt_dag' AIRFLOW_CTX_TASK_ID='run_dbt_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T13:51:54.671988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T13:51:54.671988+00:00'
[2025-01-12T13:51:55.706+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-12T13:52:01.271+0000] {logging_mixin.py:190} INFO - 13:51:58  Running with dbt=1.6.1
13:51:58  Registered adapter: postgres=1.6.1
13:52:00  Found 4 models, 2 seeds, 2 sources, 0 exposures, 0 metrics, 464 macros, 0 groups, 0 semantic models
13:52:00  
13:52:00  Concurrency: 1 threads (target='dev')
13:52:00  
13:52:00  1 of 1 START sql table model jin_schema.my_first_dbt_model ..................... [RUN]
13:52:00  1 of 1 OK created sql table model jin_schema.my_first_dbt_model ................ [SELECT 2 in 0.16s]
13:52:00  
13:52:00  Finished running 1 table model in 0 hours 0 minutes and 0.28 seconds (0.28s).
13:52:00  
13:52:00  Completed successfully
13:52:00  
13:52:00  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-01-12T13:52:01.272+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-12T13:52:01.280+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-12T13:52:01.281+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dbt_dag, task_id=run_dbt_model, run_id=manual__2025-01-12T13:51:54.671988+00:00, execution_date=20250112T135154, start_date=20250112T135155, end_date=20250112T135201
[2025-01-12T13:52:01.281+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: slack_success_callback
[2025-01-12T13:52:01.282+0000] {taskinstance.py:1567} ERROR - Error in callback at index 0: slack_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1565, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/my_first_dbt_dag.py", line 35, in slack_success_callback
    success_task_alert = SlackAPIPostOperator(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/operators/slack.py", line 159, in __init__
    super().__init__(method="chat.postMessage", **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/operators/slack.py", line 72, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 506, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 957, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SlackAPIPostOperator (task_id: slack_success_notification). Invalid arguments were:
**kwargs: {'webhook_token': 'https://hooks.slack.com/services/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'}
[2025-01-12T13:52:01.338+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-12T13:52:01.352+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-12T13:52:01.355+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
